// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/4/2026, 2:39:20 PM
const configMerger = require("/var/www/wecode-admin/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/var/www/wecode-admin/components/**/*.{vue,js,mjs}","/var/www/wecode-admin/components/**/*.{vue,js,mjs}","/var/www/wecode-admin/layouts/**/*.{vue,js,mjs}","/var/www/wecode-admin/pages/**/*.{vue,js,mjs}","/var/www/wecode-admin/composables/**/*.{js,ts,mjs}","/var/www/wecode-admin/utils/**/*.{js,ts,mjs}","/var/www/wecode-admin/{A,a}pp.{vue,js,mjs}","/var/www/wecode-admin/{E,e}rror.{vue,js,mjs}","/var/www/wecode-admin/app.config.{js,ts,mjs}"] } }));

module.exports = config
